In [1]:
import random
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split, GridSearchCV

import torch
import torch.nn as nn
import torch.optim as optim
import optuna
from torch.utils.data import DataLoader, TensorDataset

from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

from sklearn.metrics import classification_report, recall_score, precision_recall_curve, roc_auc_score, confusion_matrix, precision_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.preprocessing import PolynomialFeatures
from scipy.stats import uniform
from sklearn.base import BaseEstimator, TransformerMixin
import xgboost as xgb

/home/hle12/miniforge3/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_csv("/home/hle12/Project/Churn/EDA/post_EDA.csv")

In [3]:
df.head()

,PercChangeMinutes,RevenuePerMinute,CurrentEquipmentDays,MonthlyMinutes,EquipmentAgeRatio,DeviceToServiceAgeRatio,PeakCallsInOut,OffPeakCallsInOut,ServiceIssueRate,CallRatio,...,ReceivedCalls,UnansweredCalls,AgeHH1,TotalRecurringCharge,OutboundCalls,MonthsInService,ServiceAgeInDays,InboundCalls,CustomerCareCalls,Churn_numeric
0,-157.0,0.109091,5.891644,5.393628,0.197160,0.197160,4.077537,3.218876,0.135545,0.000000,...,4.587006,1.987874,62.0,22.0,0.000000,4.127134,7.512618,0.000000,0.000000,1
1,-4.0,1.544545,7.316548,2.397895,0.863871,0.863871,1.791759,0.693147,0.054424,0.000000,...,0.000000,1.308333,40.0,17.0,0.000000,4.077537,7.462215,0.000000,0.000000,1
2,-2.0,4.222222,7.502738,2.197225,1.006108,1.006108,0.832909,1.547563,0.000000,0.262364,...,0.336472,0.000000,26.0,38.0,0.262364,4.110874,7.496097,0.000000,0.000000,0
3,157.0,0.062666,6.129050,7.180070,0.258611,0.258611,6.322026,5.719328,1.448486,1.253342,...,5.304796,4.343805,30.0,75.0,5.917010,4.094345,7.479300,4.997212,1.667707,0
4,0.0,17.140000,6.748760,0.000000,0.535512,0.535512,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,46.0,17.0,0.000000,3.988984,7.372118,0.000000,0.000000,1

In [4]:
df['Churn_numeric'].unique()

array([1, 0])

## Explanation of Results:


### Note: Explore Different Sampling Techniques to Maximise Accuracy

- While for my previous project on domestic violence dataset only explore SMOTE as an option to address SMOTE imbalance, for this dataset I will investigate other resampling methods, including undersampling and hybrid sampling.

- I also draw insights from secondary sources, especially Fujo et al., to hone the methodology of my model.

- How did I choose my threshold? I choose it based on a basic marketing principle: "It is cheaper to keep a customer than to make one."

### Techniques Used:

2. Threshold-Moving
3. Stratified Sampling, Undersampling, Oversampling

Below is the code:

### Split data into test, train and val

In [5]:
transformed = df.copy()

In [6]:
y = transformed['Churn_numeric']
X = transformed.drop(columns = 'Churn_numeric', axis = 1)

In [7]:
y.head()

0    1
1    1
2    0
3    0
4    1
Name: Churn_numeric, dtype: int64

In [8]:
X.head()

,PercChangeMinutes,RevenuePerMinute,CurrentEquipmentDays,MonthlyMinutes,EquipmentAgeRatio,DeviceToServiceAgeRatio,PeakCallsInOut,OffPeakCallsInOut,ServiceIssueRate,CallRatio,...,TotalCalls,ReceivedCalls,UnansweredCalls,AgeHH1,TotalRecurringCharge,OutboundCalls,MonthsInService,ServiceAgeInDays,InboundCalls,CustomerCareCalls
0,-157.0,0.109091,5.891644,5.393628,0.197160,0.197160,4.077537,3.218876,0.135545,0.000000,...,4.587006,4.587006,1.987874,62.0,22.0,0.000000,4.127134,7.512618,0.000000,0.000000
1,-4.0,1.544545,7.316548,2.397895,0.863871,0.863871,1.791759,0.693147,0.054424,0.000000,...,0.000000,0.000000,1.308333,40.0,17.0,0.000000,4.077537,7.462215,0.000000,0.000000
2,-2.0,4.222222,7.502738,2.197225,1.006108,1.006108,0.832909,1.547563,0.000000,0.262364,...,0.530628,0.336472,0.000000,26.0,38.0,0.262364,4.110874,7.496097,0.000000,0.000000
3,157.0,0.062666,6.129050,7.180070,0.258611,0.258611,6.322026,5.719328,1.448486,1.253342,...,6.577305,5.304796,4.343805,30.0,75.0,5.917010,4.094345,7.479300,4.997212,1.667707
4,0.0,17.140000,6.748760,0.000000,0.535512,0.535512,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,46.0,17.0,0.000000,3.988984,7.372118,0.000000,0.000000

## Data Preparation & Transformation

The process for data preparation include:
1. Splitting data
2. Sample training data
3. Convert X and y to numpy
4. Scale X using standard scaler
5. Convert X and y to tensors

We are testing 4 different models: Logistic Regression, XGBoost, Random Forest, Neural Network. These were chosen by process of elimination and based on the progress. For example, we start with Logistic Regression, due to its simiplicity to explain to stakeholders and because the problem is that of classification. Because Logistic Regression is not suffice, we explore models that introduce non-linear relationships. XG boost was chosen because it is a top performer on tabular data and Random Forest was chosen for speed which makes it ideal for larger datasets for large firms. Lastly, Neural Network was chosen because it could capture a more complex relationship, despite requiring more computational resource.

Among these 4 models, only Neural Network needs a validation data set to prevent over-fitting so we will create a separate Train + Val + Test data set for it.

The Train data set will also have 4 different sampling techniques:
(Note that all 4 are combined with stratified sampling)

1. Original / Only Stratified
2. RandomUnderSampler
3. SMOTE
4. Smote + RUS

In [9]:
# Set scaler
scaler = MinMaxScaler()

### Train + Val +Test

In [10]:
# Stratified split into train + temp (validation+test)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Then split temp into validation and test sets (equal halves here)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42
)

In [11]:
# Convert training data to numpy for imblearn
X_train_np = X_train.values
y_train_np = y_train.values

In [12]:
X_train_np = scaler.fit_transform(X_train_np)  # Fit on original train

In [13]:
# Because we are using Pytorch, convert the dtype of sets from float64 to tensor.float32.
def to_tensor(X, y):
    X_tensor = torch.tensor(X, dtype=torch.float32)
    y_tensor = torch.tensor(y, dtype=torch.float32).unsqueeze(1)  # Add dim for BCELoss
    return X_tensor, y_tensor

In [14]:
# Transform & convert validation and test sets to tensors
X_val = scaler.transform(X_val.values)  
X_test = scaler.transform(X_test.values)

X_val_t, y_val_t = to_tensor(X_val, y_val.values)
X_test_t, y_test_t = to_tensor(X_test, y_test.values)

In [15]:
# Prepare training data 

# Original Training Data
X_train_orig_t, y_train_orig_t = to_tensor(X_train_np, y_train_np)

# Random Under Sampler
undersample = RandomUnderSampler(sampling_strategy='majority', random_state = 42)
X_train_rus_np, y_train_rus_np = undersample.fit_resample(X_train_np, y_train_np)
X_train_rus_np = scaler.fit_transform(X_train_rus_np)
X_train_rus_t, y_train_rus_t = to_tensor(X_train_rus_np, y_train_rus_np)

# Smote
smote  = SMOTE(random_state = 42)
X_train_smote_np, y_train_smote_np = smote.fit_resample(X_train_np, y_train_np)
X_train_smote_np = scaler.fit_transform(X_train_smote_np)
X_train_smote_t, y_train_smote_t = to_tensor(X_train_smote_np, y_train_smote_np)

# SMOTE + Random Under Sampler
pipeline = Pipeline([
    ('smote', smote),
    ('undersample', undersample)
])

X_train_hybrid_np, y_train_hybrid_np = pipeline.fit_resample(X_train_np, y_train_np)
X_train_hybrid_np = scaler.fit_transform(X_train_hybrid_np)
X_train_hybrid_t, y_train_hybrid_t = to_tensor(X_train_hybrid_np, y_train_hybrid_np)

## Train + Test

In [16]:
# Stratified split into train + test
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [17]:
# Because we are using Pytorch, convert the dtype of sets from float64 to tensor.float32.
def to_tensor(X, y):
    X_tensor = torch.tensor(X, dtype=torch.float32)
    y_tensor = torch.tensor(y, dtype=torch.float32).unsqueeze(1)  # Add dim for BCELoss
    return X_tensor, y_tensor

In [18]:
# Convert training data to numpy for imblearn
X_train_2_np = X_train_2.values
y_train_2_np = y_train_2.values

# Scale
X_train_2_np = scaler.fit_transform(X_train_2_np)
X_test_2_np =  scaler.transform(X_test_2.values)

# Convert validation and test sets to tensors
X_train_2_t, y_train_2_t = to_tensor(X_train_2_np, y_train_2_np)
X_test_2_t, y_test_2_t = to_tensor(X_test_2_np, y_test_2.values)

In [19]:
# Prepare training data 

# Random Under Sampler
undersample = RandomUnderSampler(sampling_strategy='majority', random_state = 42)
X_train_rus_2_np, y_train_rus_2_np = undersample.fit_resample(X_train_2_np, y_train_2_np)
X_train_rus_2_np = scaler.fit_transform(X_train_rus_2_np)
X_train_rus_2_t, y_train_rus_2_t = to_tensor(X_train_rus_2_np, y_train_rus_2_np)

# Smote
smote  = SMOTE(random_state = 42)
X_train_smote_2_np, y_train_smote_2_np = smote.fit_resample(X_train_2_np, y_train_2_np)
X_train_smote_2_np = scaler.fit_transform(X_train_smote_2_np)
X_train_smote_2_t, y_train_smote_2_t = to_tensor(X_train_smote_2_np, y_train_smote_2_np)

# SMOTE + Random Under Sampler
pipeline = Pipeline([
    ('smote', smote),
    ('undersample', undersample)
])

X_train_hybrid_2_np, y_train_hybrid_2_np = pipeline.fit_resample(X_train_2_np, y_train_2_np)
X_train_hybrid_2_np = scaler.fit_transform(X_train_hybrid_2_np)
X_train_hybrid_2_t, y_train_hybrid_2_t = to_tensor(X_train_hybrid_2_np, y_train_hybrid_2_np)

# Choosing Model

Because the size of the data set is small, simpler models are tested. This include neural network, linear regression and decision trees.

In [20]:
def create_evaluation_metrics(name, y_test, y_pred, y_pred_probs):
    # ROC AUC
    roc_auc = roc_auc_score(y_test, y_pred_probs)
    
    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    
    # Classification report 
    report = classification_report(y_test, y_pred)

    print(name)
    print("ROC AUC:", roc_auc)
    print("Confusion Matrix:\n", cm)
    print("Classification Report:\n", report)

    print("---------------------------")

In [21]:
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

### Logistic Regression

In [22]:
# Custom dummy transformer for skipping steps
class IdentityTransformer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X
pipeline = Pipeline([
    ('scaler', MinMaxScaler()),
    ('poly', PolynomialFeatures(include_bias=False)),
    ('smote', IdentityTransformer()),
    ('rus', IdentityTransformer()),
    ('clf', LogisticRegression(max_iter=300, solver='saga', class_weight='balanced'))
])

param_dist = {
    'poly__degree': [1, 2],
    'smote': [SMOTE(random_state=42), IdentityTransformer()],
    'rus': [RandomUnderSampler(random_state=42), IdentityTransformer()],
    'clf__C': uniform(0.01, 1),
    'clf__penalty': ['l1', 'l2'],
    'clf__solver': ['liblinear', 'saga']
}

random_search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_dist,
    n_iter=30,
    cv=5,
    scoring='roc_auc',
    n_jobs=-1,
    verbose=2,
    random_state=42
)

random_search.fit(X_train_2_np, y_train_2_np.ravel())


print("Best params:", random_search.best_params_)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/hle12/miniforge3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=0.3845401188473625, clf__penalty=l1, clf__solver=liblinear, poly__degree=1, rus=IdentityTransformer(), smote=SMOTE(random_state=42); total time=17.7min
[CV] END clf__C=0.48537022318211176, clf__penalty=l1, clf__solver=saga, poly__degree=2, rus=IdentityTransformer(), smote=SMOTE(random_state=42); total time= 2.9min
[CV] END clf__C=0.06641157902710025, clf__penalty=l2, clf__solver=saga, poly__degree=2, rus=IdentityTransformer(), smote=IdentityTransformer(); total time=   5.8s
[CV] END clf__C=0.017066305219717408, clf__penalty=l1, clf__solver=liblinear, poly__degree=1, rus=RandomUnderSampler(random_state=42), smote=SMOTE(random_state=42); total time=   2.4s
[CV] END clf__C=0.14949386065204184, clf__penalty=l2, clf__solver=saga, poly__degree=2, rus=RandomUnderSampler(random_state=42), smote=IdentityTransformer(); total time=   6.1s
[CV] END clf__C=0.14949386065204184, clf__penalty=l2, clf__solver=saga, poly__degree=2, rus=RandomUnderSampler(random_state=42), smote=IdentityTransformer(); total time=   5.4s
[CV] END clf__C=0.460499251969543, clf__penalty=l2, clf__solver=saga, poly__degree=1, rus=IdentityTransformer(), smote=IdentityTransformer(); total time=   1.0s
[CV] END clf__C=0.460499251969543, clf__penalty=l2, clf__solver=saga, poly__degree=1, rus=IdentityTransformer(), smote=IdentityTransformer(); total time=   1.4s
[CV] END clf__C=0.8183973481164611, clf__penalty=l1, clf__solver=saga, poly__degree=1, rus=IdentityTransformer(), smote=IdentityTransformer(); total time=  24.1s
[CV] END clf__C=0.19485445552552705, clf__penalty=l1, clf__solver=saga, poly__degree=2, rus=IdentityTransformer(), smote=IdentityTransformer(); total time= 2.8min
[CV] END clf__C=0.28472179299006417, clf__penalty=l1, clf__solver=liblinear, poly__degree=1, rus=RandomUnderSampler(random_state=42), smote=SMOTE(random_state=42); total time=14.4min
[CV] END clf__C=0.48537022318211176, clf__penalty=l1, clf__solver=saga, poly__degree=2, rus=IdentityTransformer(), smote=SMOTE(random_state=42); total time= 3.1min
Best params: {'clf__C': np.float64(0.7653614103176525), 'clf__penalty': 'l2', 'clf__solver': 'saga', 'poly__degree': 2, 'rus': IdentityTransformer(), 'smote': IdentityTransformer()}

In [29]:
best_model = random_search.best_estimator_
y_probs = best_model.predict_proba(X_test_2_t)[:, 1]
y_pred = (y_probs >= 0.54).astype(int)

create_evaluation_metrics("RandomSearch + SMOTE + Poly + LR", y_test_2_t, y_pred, y_probs)

RandomSearch + SMOTE + Poly + LR
ROC AUC: 0.6115213799574755
Confusion Matrix:
 [[5097 2171]
 [1680 1262]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.75      0.70      0.73      7268
         1.0       0.37      0.43      0.40      2942

    accuracy                           0.62     10210
   macro avg       0.56      0.57      0.56     10210
weighted avg       0.64      0.62      0.63     10210

---------------------------

### Random Forest Classifier

In [52]:
param_grid = {
    'n_estimators': [100, 200],             # Number of trees in the forest
    'max_depth': [5, 10, 15, 20, None],     # Max depth of trees
    'min_samples_leaf': [1, 2, 5, 10],      # Minimum samples at a leaf node
    'min_samples_split': [2, 5, 10],        # Minimum samples to split a node
    'max_features': ['sqrt', 'log2'],       # Features to consider at each split
}

rf = RandomForestClassifier(random_state=42)

grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, scoring='roc_auc', n_jobs=-1)
grid_search.fit(X_train_2_t, y_train_2_t.ravel())

print(grid_search.best_params_)     # Then access best params
best_rf = grid_search.best_estimator_  # Then access best estimator

{'max_depth': 15, 'max_features': 'sqrt', 'min_samples_leaf': 10, 'min_samples_split': 2, 'n_estimators': 200}

In [30]:
def create_RFC(name, X_train, y_train, weight=None, threshold=0.5):
    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=15,
        max_features='sqrt',
        min_samples_leaf=10,
        min_samples_split=2,
        random_state=42,
        class_weight=weight
    )
    model.fit(X_train, y_train) 

    y_probs = model.predict_proba(X_test_2_t)[:, 1]

    y_pred = (y_probs >= threshold).astype(int)

    print(name)
    create_evaluation_metrics(model, y_test_2_t, y_pred, y_probs)

    return model

In [31]:
# Stratified / Original
create_RFC('Stratified', X_train_2_t, y_train_2_t.ravel(), weight='balanced', threshold = 0.53)

Stratified
RandomForestClassifier(class_weight='balanced', max_depth=15,
                       min_samples_leaf=10, n_estimators=200, random_state=42)
ROC AUC: 0.6495248721662282
Confusion Matrix:
 [[5596 1672]
 [1702 1240]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.77      0.77      0.77      7268
         1.0       0.43      0.42      0.42      2942

    accuracy                           0.67     10210
   macro avg       0.60      0.60      0.60     10210
weighted avg       0.67      0.67      0.67     10210

---------------------------

RandomForestClassifier(class_weight='balanced', max_depth=15,
                       min_samples_leaf=10, n_estimators=200, random_state=42)

In [32]:
# RandomUnderSampler
create_RFC('RandomUnderSampler', X_train_rus_2_t, y_train_rus_2_t.ravel(), threshold = 0.58)

RandomUnderSampler
RandomForestClassifier(max_depth=15, min_samples_leaf=10, n_estimators=200,
                       random_state=42)
ROC AUC: 0.6326732064829222
Confusion Matrix:
 [[3940 3328]
 [1045 1897]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.79      0.54      0.64      7268
         1.0       0.36      0.64      0.46      2942

    accuracy                           0.57     10210
   macro avg       0.58      0.59      0.55     10210
weighted avg       0.67      0.57      0.59     10210

---------------------------

RandomForestClassifier(max_depth=15, min_samples_leaf=10, n_estimators=200,
                       random_state=42)

In [35]:
# SMOTE
create_RFC('SMOTE', X_train_smote_2_t, y_train_smote_2_t.ravel(), threshold = 0.50)

SMOTE
RandomForestClassifier(max_depth=15, min_samples_leaf=10, n_estimators=200,
                       random_state=42)
ROC AUC: 0.6391284518485622
Confusion Matrix:
 [[5098 2170]
 [1524 1418]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.77      0.70      0.73      7268
         1.0       0.40      0.48      0.43      2942

    accuracy                           0.64     10210
   macro avg       0.58      0.59      0.58     10210
weighted avg       0.66      0.64      0.65     10210

---------------------------

RandomForestClassifier(max_depth=15, min_samples_leaf=10, n_estimators=200,
                       random_state=42)

In [34]:
# SMOTE + RUS
create_RFC('SMOTE + RUS', X_train_hybrid_2_t, y_train_hybrid_2_t.ravel(), threshold = 0.55)

SMOTE + RUS
RandomForestClassifier(max_depth=15, min_samples_leaf=10, n_estimators=200,
                       random_state=42)
ROC AUC: 0.6385883829247678
Confusion Matrix:
 [[6170 1098]
 [2127  815]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.74      0.85      0.79      7268
         1.0       0.43      0.28      0.34      2942

    accuracy                           0.68     10210
   macro avg       0.58      0.56      0.56     10210
weighted avg       0.65      0.68      0.66     10210

---------------------------

RandomForestClassifier(max_depth=15, min_samples_leaf=10, n_estimators=200,
                       random_state=42)

### XGBoost

In [24]:
def objective(trial):
    param = {
        'verbosity': 0,
        'objective': 'binary:logistic',
        'eval_metric': 'auc',
        'use_label_encoder': False,
        'tree_method': 'hist',
        'max_depth': trial.suggest_int('max_depth', 3, 8),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1, 3)
    }
    
    model = xgb.XGBClassifier(**param, n_estimators=500, random_state=42)
    model.fit(X_train_orig_t, y_train_orig_t)
    
    preds = model.predict_proba(X_val_t)[:, 1]
    auc = roc_auc_score(y_val_t, preds)
    
    return auc

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

print("Best trial:")
trial = study.best_trial
print(f"  AUC: {trial.value:.4f}")
print("  Params:")
for key, value in trial.params.items():
    print(f"    {key}: {value}")

[I 2025-10-15 21:22:54,987] A new study created in memory with name: no-name-a38ab34a-d028-4a0a-acbe-9b59609dda40
[I 2025-10-15 21:22:56,040] Trial 0 finished with value: 0.6534651585393184 and parameters: {'max_depth': 4, 'learning_rate': 0.013612434250023375, 'subsample': 0.7980018178069564, 'colsample_bytree': 0.733761020806961, 'min_child_weight': 5, 'gamma': 2.9807090602928836, 'scale_pos_weight': 2.328762960559365}. Best is trial 0 with value: 0.6534651585393184.
[I 2025-10-15 21:22:56,753] Trial 1 finished with value: 0.6516814532437246 and parameters: {'max_depth': 8, 'learning_rate': 0.10445192296024573, 'subsample': 0.739174898410369, 'colsample_bytree': 0.6032989393181005, 'min_child_weight': 6, 'gamma': 4.7209164487886826, 'scale_pos_weight': 1.1303516151255706}. Best is trial 0 with value: 0.6534651585393184.
[I 2025-10-15 21:22:58,067] Trial 2 finished with value: 0.6563449961033476 and parameters: {'max_depth': 6, 'learning_rate': 0.027431356799654097, 'subsample': 0.6318038805422632, 'colsample_bytree': 0.9658708474899997, 'min_child_weight': 5, 'gamma': 0.9927755733629873, 'scale_pos_weight': 2.778376407574765}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:22:59,366] Trial 3 finished with value: 0.6498825018042831 and parameters: {'max_depth': 8, 'learning_rate': 0.047318207474504805, 'subsample': 0.6598416755740453, 'colsample_bytree': 0.8736308298105521, 'min_child_weight': 8, 'gamma': 4.906234286171884, 'scale_pos_weight': 2.3352478730542137}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:00,282] Trial 4 finished with value: 0.6525723705452732 and parameters: {'max_depth': 5, 'learning_rate': 0.0567442162234708, 'subsample': 0.876109353812919, 'colsample_bytree': 0.6875774866926898, 'min_child_weight': 6, 'gamma': 1.2389024828083999, 'scale_pos_weight': 2.1621818767716983}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:01,086] Trial 5 finished with value: 0.6545293955006852 and parameters: {'max_depth': 4, 'learning_rate': 0.02614044768468542, 'subsample': 0.8803143947103245, 'colsample_bytree': 0.6594813698101191, 'min_child_weight': 5, 'gamma': 2.7973863817196145, 'scale_pos_weight': 1.2974958121673958}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:01,788] Trial 6 finished with value: 0.627658674943608 and parameters: {'max_depth': 4, 'learning_rate': 0.2603586537841947, 'subsample': 0.7792635356636983, 'colsample_bytree': 0.7827688434665503, 'min_child_weight': 2, 'gamma': 3.6317770569935313, 'scale_pos_weight': 2.3404921743314686}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:03,280] Trial 7 finished with value: 0.6519170669636828 and parameters: {'max_depth': 7, 'learning_rate': 0.030776716935666405, 'subsample': 0.9264190508208031, 'colsample_bytree': 0.8682353244153671, 'min_child_weight': 2, 'gamma': 1.5282621304945176, 'scale_pos_weight': 1.0349117165899202}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:03,910] Trial 8 finished with value: 0.6418996957131585 and parameters: {'max_depth': 6, 'learning_rate': 0.24363090307996998, 'subsample': 0.7542398755583252, 'colsample_bytree': 0.8468649153025712, 'min_child_weight': 9, 'gamma': 4.951311351262258, 'scale_pos_weight': 1.523263559734407}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:05,144] Trial 9 finished with value: 0.6268514711312863 and parameters: {'max_depth': 6, 'learning_rate': 0.1140554225052121, 'subsample': 0.8342739215999456, 'colsample_bytree': 0.8758244428515838, 'min_child_weight': 7, 'gamma': 1.6106053054962644, 'scale_pos_weight': 2.870788182334917}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:05,806] Trial 10 finished with value: 0.6481820423247919 and parameters: {'max_depth': 3, 'learning_rate': 0.011192111268996014, 'subsample': 0.6015300317217009, 'colsample_bytree': 0.9948853469150153, 'min_child_weight': 3, 'gamma': 0.214327466352771, 'scale_pos_weight': 2.936336861176906}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:07,016] Trial 11 finished with value: 0.6550582402694993 and parameters: {'max_depth': 5, 'learning_rate': 0.022823351707876232, 'subsample': 0.9768381327121546, 'colsample_bytree': 0.9977104394772661, 'min_child_weight': 4, 'gamma': 2.6274799955080748, 'scale_pos_weight': 1.597955872654059}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:08,116] Trial 12 finished with value: 0.65590276439713 and parameters: {'max_depth': 5, 'learning_rate': 0.020436156460059446, 'subsample': 0.9767768008705777, 'colsample_bytree': 0.9800903337611885, 'min_child_weight': 4, 'gamma': 0.3068909768191438, 'scale_pos_weight': 1.6861996810330047}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:09,947] Trial 13 finished with value: 0.6504680285557468 and parameters: {'max_depth': 7, 'learning_rate': 0.019666055248595313, 'subsample': 0.9953575514849307, 'colsample_bytree': 0.9403522932416812, 'min_child_weight': 1, 'gamma': 0.02756471618513462, 'scale_pos_weight': 1.9234681686824047}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:11,312] Trial 14 finished with value: 0.648811530349928 and parameters: {'max_depth': 6, 'learning_rate': 0.0451362979889804, 'subsample': 0.6903111670354503, 'colsample_bytree': 0.9424583369429256, 'min_child_weight': 4, 'gamma': 0.8727388982333104, 'scale_pos_weight': 2.6862474069883895}. Best is trial 2 with value: 0.6563449961033476.
[I 2025-10-15 21:23:12,455] Trial 15 finished with value: 0.6583333551580791 and parameters: {'max_depth': 5, 'learning_rate': 0.01724660591794138, 'subsample': 0.6011359133165541, 'colsample_bytree': 0.9436199477029895, 'min_child_weight': 4, 'gamma': 0.8790588380161987, 'scale_pos_weight': 1.8385539783908933}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:14,137] Trial 16 finished with value: 0.6553157410916688 and parameters: {'max_depth': 7, 'learning_rate': 0.01411188661605578, 'subsample': 0.6133166670333541, 'colsample_bytree': 0.8085108828152393, 'min_child_weight': 10, 'gamma': 2.0346871164177838, 'scale_pos_weight': 1.918943967984387}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:14,900] Trial 17 finished with value: 0.6553411825096238 and parameters: {'max_depth': 3, 'learning_rate': 0.037823888566406214, 'subsample': 0.6715215012612469, 'colsample_bytree': 0.9225330913987849, 'min_child_weight': 7, 'gamma': 0.6976282637842436, 'scale_pos_weight': 2.5790312114874983}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:16,283] Trial 18 finished with value: 0.6481457508903561 and parameters: {'max_depth': 5, 'learning_rate': 0.07098409397758307, 'subsample': 0.7080014393050555, 'colsample_bytree': 0.9096097662946047, 'min_child_weight': 3, 'gamma': 2.0613374620389244, 'scale_pos_weight': 1.7969709307543058}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:18,310] Trial 19 finished with value: 0.6569484815027797 and parameters: {'max_depth': 6, 'learning_rate': 0.01620830051744609, 'subsample': 0.6389544621607732, 'colsample_bytree': 0.8116710005210706, 'min_child_weight': 7, 'gamma': 0.9078565912881377, 'scale_pos_weight': 2.121050238603736}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:20,139] Trial 20 finished with value: 0.6579203062548101 and parameters: {'max_depth': 7, 'learning_rate': 0.010277165555001699, 'subsample': 0.6433818306472805, 'colsample_bytree': 0.7946432176356346, 'min_child_weight': 8, 'gamma': 3.9569183132990644, 'scale_pos_weight': 2.150572756396506}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:23,131] Trial 21 finished with value: 0.6577324887281424 and parameters: {'max_depth': 7, 'learning_rate': 0.01571895974553528, 'subsample': 0.6376217231201187, 'colsample_bytree': 0.7795778089660826, 'min_child_weight': 8, 'gamma': 3.871473094462275, 'scale_pos_weight': 2.1266339485692254}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:24,965] Trial 22 finished with value: 0.6578131155747498 and parameters: {'max_depth': 7, 'learning_rate': 0.010961650161424202, 'subsample': 0.7226776808655604, 'colsample_bytree': 0.7621269974214706, 'min_child_weight': 9, 'gamma': 3.928886222795871, 'scale_pos_weight': 2.026923526480158}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:27,254] Trial 23 finished with value: 0.6576223984747122 and parameters: {'max_depth': 8, 'learning_rate': 0.010555640688100831, 'subsample': 0.7148473572953046, 'colsample_bytree': 0.7386957823396187, 'min_child_weight': 10, 'gamma': 4.194219885661031, 'scale_pos_weight': 1.3966159256655013}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:29,074] Trial 24 finished with value: 0.6580877332332639 and parameters: {'max_depth': 7, 'learning_rate': 0.011384445272429199, 'subsample': 0.6739936986716651, 'colsample_bytree': 0.7384790053698056, 'min_child_weight': 9, 'gamma': 3.394613961867498, 'scale_pos_weight': 1.8878137030986157}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:31,185] Trial 25 finished with value: 0.6573443200350793 and parameters: {'max_depth': 8, 'learning_rate': 0.010312830294000465, 'subsample': 0.6752613217193587, 'colsample_bytree': 0.6983929461785245, 'min_child_weight': 9, 'gamma': 3.267044337095738, 'scale_pos_weight': 1.75527231196918}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:32,954] Trial 26 finished with value: 0.655445567150939 and parameters: {'max_depth': 7, 'learning_rate': 0.017933685770974313, 'subsample': 0.6072310432853121, 'colsample_bytree': 0.8297426542714385, 'min_child_weight': 8, 'gamma': 3.325021231751175, 'scale_pos_weight': 2.4869134043384875}. Best is trial 15 with value: 0.6583333551580791.
[I 2025-10-15 21:23:34,390] Trial 27 finished with value: 0.6585699977589103 and parameters: {'max_depth': 6, 'learning_rate': 0.01339673112907882, 'subsample': 0.6462587959957571, 'colsample_bytree': 0.7271651088043469, 'min_child_weight': 10, 'gamma': 4.2664072657631555, 'scale_pos_weight': 1.8708571562978937}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:35,485] Trial 28 finished with value: 0.6555941001351763 and parameters: {'max_depth': 5, 'learning_rate': 0.03411719746517389, 'subsample': 0.6882191256707728, 'colsample_bytree': 0.6326146917219418, 'min_child_weight': 10, 'gamma': 2.206617868754227, 'scale_pos_weight': 1.8824045607256739}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:36,738] Trial 29 finished with value: 0.6547457410879275 and parameters: {'max_depth': 4, 'learning_rate': 0.015670381512912102, 'subsample': 0.7845826384528017, 'colsample_bytree': 0.7178675352032521, 'min_child_weight': 9, 'gamma': 4.41545868759346, 'scale_pos_weight': 1.5614266843749351}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:38,128] Trial 30 finished with value: 0.656402426362996 and parameters: {'max_depth': 6, 'learning_rate': 0.012863666321649665, 'subsample': 0.8117904868956896, 'colsample_bytree': 0.7520786632480363, 'min_child_weight': 10, 'gamma': 3.327389183829712, 'scale_pos_weight': 1.3259778000347204}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:40,242] Trial 31 finished with value: 0.6573605015251757 and parameters: {'max_depth': 7, 'learning_rate': 0.013117851150477448, 'subsample': 0.648680685282422, 'colsample_bytree': 0.7122956370672349, 'min_child_weight': 8, 'gamma': 4.3643404043607665, 'scale_pos_weight': 2.2315483207827906}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:42,137] Trial 32 finished with value: 0.6581547040246453 and parameters: {'max_depth': 6, 'learning_rate': 0.013174890799850411, 'subsample': 0.6258625434871898, 'colsample_bytree': 0.6696647019654212, 'min_child_weight': 6, 'gamma': 3.614166739762149, 'scale_pos_weight': 1.8141451148774865}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:43,350] Trial 33 finished with value: 0.6561933764764908 and parameters: {'max_depth': 6, 'learning_rate': 0.023571441378356126, 'subsample': 0.6212352079245712, 'colsample_bytree': 0.6666006784710958, 'min_child_weight': 6, 'gamma': 3.1130853398090155, 'scale_pos_weight': 2.0157637869770757}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:44,538] Trial 34 finished with value: 0.6581432928004155 and parameters: {'max_depth': 6, 'learning_rate': 0.019131305829771357, 'subsample': 0.7561992806598727, 'colsample_bytree': 0.6226941497654919, 'min_child_weight': 5, 'gamma': 3.6185616943356136, 'scale_pos_weight': 1.706128685488117}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:45,698] Trial 35 finished with value: 0.6568194972551329 and parameters: {'max_depth': 5, 'learning_rate': 0.01999456865785318, 'subsample': 0.7308513321311423, 'colsample_bytree': 0.6024395327768366, 'min_child_weight': 5, 'gamma': 4.581437058726138, 'scale_pos_weight': 1.7363057918509381}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:46,967] Trial 36 finished with value: 0.6552756147376149 and parameters: {'max_depth': 6, 'learning_rate': 0.026309449860468077, 'subsample': 0.6250614896287399, 'colsample_bytree': 0.633620412563374, 'min_child_weight': 6, 'gamma': 2.3581354836633746, 'scale_pos_weight': 1.4602110281645526}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:47,900] Trial 37 finished with value: 0.6492184995025829 and parameters: {'max_depth': 4, 'learning_rate': 0.1198841166538828, 'subsample': 0.748487025703023, 'colsample_bytree': 0.6294589481269613, 'min_child_weight': 3, 'gamma': 2.8936021041169773, 'scale_pos_weight': 1.676233558462185}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:48,668] Trial 38 finished with value: 0.6482484519084244 and parameters: {'max_depth': 5, 'learning_rate': 0.07471225563223549, 'subsample': 0.6583872038018086, 'colsample_bytree': 0.6678590549751502, 'min_child_weight': 4, 'gamma': 3.672141951787762, 'scale_pos_weight': 1.2492688993662493}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:49,849] Trial 39 finished with value: 0.6547621096472734 and parameters: {'max_depth': 6, 'learning_rate': 0.030354099865450533, 'subsample': 0.8387784658948723, 'colsample_bytree': 0.6822671465354642, 'min_child_weight': 5, 'gamma': 4.729290907467096, 'scale_pos_weight': 1.8223338015012989}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:50,939] Trial 40 finished with value: 0.6563204900316408 and parameters: {'max_depth': 5, 'learning_rate': 0.013785232047400096, 'subsample': 0.7664911984137232, 'colsample_bytree': 0.6217978961553718, 'min_child_weight': 6, 'gamma': 4.172521765539327, 'scale_pos_weight': 2.260138517835174}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:52,292] Trial 41 finished with value: 0.6572536849836146 and parameters: {'max_depth': 6, 'learning_rate': 0.012449105926965869, 'subsample': 0.6946680830969585, 'colsample_bytree': 0.6483946685799167, 'min_child_weight': 5, 'gamma': 3.6361847028182677, 'scale_pos_weight': 1.6370765494814008}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:53,617] Trial 42 finished with value: 0.6556366583894759 and parameters: {'max_depth': 6, 'learning_rate': 0.017044101326381678, 'subsample': 0.6607636862587954, 'colsample_bytree': 0.706165468014427, 'min_child_weight': 4, 'gamma': 3.4258577845178313, 'scale_pos_weight': 1.995480901796961}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:54,974] Trial 43 finished with value: 0.6273186765823345 and parameters: {'max_depth': 6, 'learning_rate': 0.15849598089429587, 'subsample': 0.6232470957756275, 'colsample_bytree': 0.7258709857731324, 'min_child_weight': 7, 'gamma': 2.940874265307806, 'scale_pos_weight': 1.854600956153321}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:56,960] Trial 44 finished with value: 0.6541282254947701 and parameters: {'max_depth': 8, 'learning_rate': 0.022884889648187762, 'subsample': 0.6754376211179051, 'colsample_bytree': 0.686849339181141, 'min_child_weight': 9, 'gamma': 2.6608922804283544, 'scale_pos_weight': 1.968826338801739}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:58,092] Trial 45 finished with value: 0.6561504440836917 and parameters: {'max_depth': 5, 'learning_rate': 0.014838299708149401, 'subsample': 0.6086701943515895, 'colsample_bytree': 0.7494813406720963, 'min_child_weight': 3, 'gamma': 1.7349177946984882, 'scale_pos_weight': 1.542032706171565}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:23:58,981] Trial 46 finished with value: 0.6561225707654911 and parameters: {'max_depth': 4, 'learning_rate': 0.018506759583678718, 'subsample': 0.6021485942259828, 'colsample_bytree': 0.7668080606976314, 'min_child_weight': 2, 'gamma': 3.506047033716941, 'scale_pos_weight': 1.7212557031464462}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:24:00,906] Trial 47 finished with value: 0.6580682780312982 and parameters: {'max_depth': 7, 'learning_rate': 0.012302169639798511, 'subsample': 0.7014890925302986, 'colsample_bytree': 0.649745154584706, 'min_child_weight': 4, 'gamma': 1.3040600733505723, 'scale_pos_weight': 2.058549725832981}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:24:02,016] Trial 48 finished with value: 0.6566144693574957 and parameters: {'max_depth': 5, 'learning_rate': 0.02038908203074341, 'subsample': 0.6575897955174135, 'colsample_bytree': 0.7362344272073127, 'min_child_weight': 6, 'gamma': 3.73616505435812, 'scale_pos_weight': 1.4837858588327775}. Best is trial 27 with value: 0.6585699977589103.
[I 2025-10-15 21:24:03,331] Trial 49 finished with value: 0.6540861349135946 and parameters: {'max_depth': 6, 'learning_rate': 0.040224492502475166, 'subsample': 0.8827174483508031, 'colsample_bytree': 0.896855428585087, 'min_child_weight': 5, 'gamma': 4.0650546331960005, 'scale_pos_weight': 2.4033174264426527}. Best is trial 27 with value: 0.6585699977589103.

Best trial:
  AUC: 0.6586
  Params:
    max_depth: 6
    learning_rate: 0.01339673112907882
    subsample: 0.6462587959957571
    colsample_bytree: 0.7271651088043469
    min_child_weight: 10
    gamma: 4.2664072657631555
    scale_pos_weight: 1.8708571562978937

In [38]:
create_XGBoost('Original', X_train_2_t, y_train_2_t.ravel(), scale_pos_weight= 1.8708571562978937, threshold = 0.48)

/home/hle12/miniforge3/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [21:26:25] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Original
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7271651088043469, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=4.2664072657631555, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01339673112907882,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=10, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)
ROC AUC: 0.6558071252432368
Confusion Matrix:
 [[5387 1881]
 [1582 1360]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.77      0.74      0.76      7268
         1.0       0.42      0.46      0.44      2942

    accuracy                           0.66     10210
   macro avg       0.60      0.60      0.60     10210
weighted avg       0.67      0.66      0.67     10210

---------------------------

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7271651088043469, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=4.2664072657631555, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01339673112907882,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=10, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [33]:
def create_XGBoost(name, X_train, y_train, scale_pos_weight = 1, threshold = 0.5):
    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate= 0.01339673112907882,
        subsample= 0.6462587959957571,
        colsample_bytree= 0.7271651088043469,
        scale_pos_weight= scale_pos_weight, 
        random_state=42,
        use_label_encoder=False,
        gamma =  4.2664072657631555,
        min_child_weight = 10,
        eval_metric='logloss'
    )
    model.fit(X_train, y_train)

    y_probs = model.predict_proba(X_test_2_t)[:, 1]
    y_pred = (y_probs >= threshold).astype(int)

    print(name)
    create_evaluation_metrics(model, y_test_2_t, y_pred, y_probs)

    return model

In [46]:
create_XGBoost('RUS', X_train_rus_2_t, y_train_rus_2_t.ravel(), threshold = 0.63)

/home/hle12/miniforge3/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [21:27:40] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

RUS
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7271651088043469, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=4.2664072657631555, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01339673112907882,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=10, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)
ROC AUC: 0.630919362116307
Confusion Matrix:
 [[4584 2684]
 [1303 1639]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.78      0.63      0.70      7268
         1.0       0.38      0.56      0.45      2942

    accuracy                           0.61     10210
   macro avg       0.58      0.59      0.57     10210
weighted avg       0.66      0.61      0.63     10210

---------------------------

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7271651088043469, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=4.2664072657631555, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01339673112907882,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=10, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [47]:
create_XGBoost('SMOTE', X_train_smote_2_t, y_train_smote_2_t.ravel())

/home/hle12/miniforge3/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [21:28:16] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

SMOTE
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7271651088043469, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=4.2664072657631555, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01339673112907882,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=10, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)
ROC AUC: 0.6303289014133829
Confusion Matrix:
 [[5182 2086]
 [1634 1308]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.76      0.71      0.74      7268
         1.0       0.39      0.44      0.41      2942

    accuracy                           0.64     10210
   macro avg       0.57      0.58      0.57     10210
weighted avg       0.65      0.64      0.64     10210

---------------------------

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7271651088043469, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=4.2664072657631555, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01339673112907882,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=10, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [48]:
create_XGBoost('hybrid', X_train_hybrid_2_t, y_train_hybrid_2_t.ravel())

/home/hle12/miniforge3/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [21:28:17] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

hybrid
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7271651088043469, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=4.2664072657631555, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01339673112907882,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=10, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)
ROC AUC: 0.6285483529113775
Confusion Matrix:
 [[5174 2094]
 [1628 1314]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.76      0.71      0.74      7268
         1.0       0.39      0.45      0.41      2942

    accuracy                           0.64     10210
   macro avg       0.57      0.58      0.57     10210
weighted avg       0.65      0.64      0.64     10210

---------------------------

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7271651088043469, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=4.2664072657631555, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01339673112907882,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=10, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

### Neural Networks

In [23]:
def objective(trial):
    set_seed(42)

    # Hyperparameters 
    hidden_size1 = trial.suggest_int("hidden_size1", 64, 512, step=32)
    hidden_size2 = trial.suggest_int("hidden_size2", 8, 256, step=8)
    lr = trial.suggest_float("lr", 1e-5, 1e-2, log=True)
    activation_name = trial.suggest_categorical("activation", ["ReLU", "Tanh", "LeakyReLU"])

    # Activation function
    activation = {
        "ReLU": nn.ReLU(),
        "Tanh": nn.Tanh(),
        "LeakyReLU": nn.LeakyReLU()
    }[activation_name]

    # Model
    model = nn.Sequential(
        nn.Linear(21, hidden_size1),
        activation,
        nn.Linear(hidden_size1, hidden_size2),
        activation,
        nn.Linear(hidden_size2, 1),
        nn.Sigmoid()
    )

    model.to('cpu')  # or 'cuda' if using GPU
    optimizer = optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.BCELoss()

    patience = 10
    best_f1 = 0
    epochs_no_improve = 0

    for epoch in range(100):
        # Train
        model.train()
        y_pred = model(X_train_rus_t).squeeze(1)
        loss = loss_fn(y_pred, y_train_rus_t.squeeze(1))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Evaluate on validation set
        model.eval()
        with torch.no_grad():
            val_probs = model(X_val_t).squeeze(1).numpy()
            val_preds = (val_probs >= 0.5).astype(int)
            y_val_np = y_val_t.squeeze(1).numpy()
            f1 = f1_score(y_val_np, val_preds, zero_division=0)

        # Early stopping on F1
        if f1 > best_f1:
            best_f1 = f1
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1
            if epochs_no_improve >= patience:
                break

    return best_f1

[CV] END clf__C=0.3845401188473625, clf__penalty=l1, clf__solver=liblinear, poly__degree=1, rus=IdentityTransformer(), smote=SMOTE(random_state=42); total time=24.5min
[CV] END clf__C=0.3845401188473625, clf__penalty=l1, clf__solver=liblinear, poly__degree=1, rus=IdentityTransformer(), smote=SMOTE(random_state=42); total time=25.1min
[CV] END clf__C=0.3845401188473625, clf__penalty=l1, clf__solver=liblinear, poly__degree=1, rus=IdentityTransformer(), smote=SMOTE(random_state=42); total time=24.3min
[CV] END clf__C=0.606850157946487, clf__penalty=l2, clf__solver=liblinear, poly__degree=1, rus=RandomUnderSampler(random_state=42), smote=SMOTE(random_state=42); total time=   3.0s
[CV] END clf__C=0.017066305219717408, clf__penalty=l1, clf__solver=liblinear, poly__degree=1, rus=RandomUnderSampler(random_state=42), smote=SMOTE(random_state=42); total time=  13.4s
[CV] END clf__C=0.14949386065204184, clf__penalty=l2, clf__solver=saga, poly__degree=2, rus=RandomUnderSampler(random_state=42), smote=IdentityTransformer(); total time=  20.3s
[CV] END clf__C=0.2510254660260117, clf__penalty=l2, clf__solver=liblinear, poly__degree=2, rus=RandomUnderSampler(random_state=42), smote=IdentityTransformer(); total time=  15.1s
[CV] END clf__C=0.0443885211152184, clf__penalty=l2, clf__solver=liblinear, poly__degree=2, rus=IdentityTransformer(), smote=IdentityTransformer(); total time=  23.2s
[CV] END clf__C=0.19485445552552705, clf__penalty=l1, clf__solver=saga, poly__degree=2, rus=IdentityTransformer(), smote=IdentityTransformer(); total time= 1.7min
[CV] END clf__C=0.3062735057040824, clf__penalty=l1, clf__solver=liblinear, poly__degree=1, rus=RandomUnderSampler(random_state=42), smote=SMOTE(random_state=42); total time=21.2min

In [24]:
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50)
print("Best hyperparameters:", study.best_params)

[I 2025-10-16 20:16:48,317] A new study created in memory with name: no-name-79ab842a-a127-4735-ba11-47f10ceb02e8
[I 2025-10-16 20:16:52,876] Trial 0 finished with value: 0.44754173686628884 and parameters: {'hidden_size1': 416, 'hidden_size2': 128, 'lr': 0.007761561711965477, 'activation': 'LeakyReLU'}. Best is trial 0 with value: 0.44754173686628884.
[I 2025-10-16 20:16:53,268] Trial 1 finished with value: 0.4495631453534551 and parameters: {'hidden_size1': 160, 'hidden_size2': 104, 'lr': 0.0005178935584870791, 'activation': 'Tanh'}. Best is trial 1 with value: 0.4495631453534551.
[I 2025-10-16 20:16:53,697] Trial 2 finished with value: 0.4556586270871985 and parameters: {'hidden_size1': 160, 'hidden_size2': 104, 'lr': 0.007781495749155925, 'activation': 'Tanh'}. Best is trial 2 with value: 0.4556586270871985.
[I 2025-10-16 20:16:54,374] Trial 3 finished with value: 0.45652173913043476 and parameters: {'hidden_size1': 256, 'hidden_size2': 112, 'lr': 0.00041270826662052716, 'activation': 'ReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:16:55,473] Trial 4 finished with value: 0.42212709911096474 and parameters: {'hidden_size1': 384, 'hidden_size2': 224, 'lr': 5.195775099681551e-05, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:16:55,773] Trial 5 finished with value: 0.4207182995357928 and parameters: {'hidden_size1': 96, 'hidden_size2': 128, 'lr': 0.00016589204138873603, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:16:55,930] Trial 6 finished with value: 0.0 and parameters: {'hidden_size1': 96, 'hidden_size2': 40, 'lr': 0.00010249303714183922, 'activation': 'LeakyReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:16:56,362] Trial 7 finished with value: 0.0 and parameters: {'hidden_size1': 448, 'hidden_size2': 16, 'lr': 6.752647143994054e-05, 'activation': 'LeakyReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:16:57,253] Trial 8 finished with value: 0.4404631854926808 and parameters: {'hidden_size1': 320, 'hidden_size2': 160, 'lr': 1.7392830711077487e-05, 'activation': 'ReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:16:57,880] Trial 9 finished with value: 0.455325232308792 and parameters: {'hidden_size1': 384, 'hidden_size2': 16, 'lr': 0.002086275647845059, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:16:59,311] Trial 10 finished with value: 0.4429727740986019 and parameters: {'hidden_size1': 256, 'hidden_size2': 256, 'lr': 0.0007523313199020728, 'activation': 'ReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:16:59,612] Trial 11 finished with value: 0.4520475093068605 and parameters: {'hidden_size1': 224, 'hidden_size2': 80, 'lr': 0.008303586856661407, 'activation': 'ReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:00,309] Trial 12 finished with value: 0.4465423648808119 and parameters: {'hidden_size1': 192, 'hidden_size2': 176, 'lr': 0.0022583554656096638, 'activation': 'ReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:01,802] Trial 13 finished with value: 0.4533103299547121 and parameters: {'hidden_size1': 320, 'hidden_size2': 80, 'lr': 0.0016657766332734524, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:02,147] Trial 14 finished with value: 0.44739654909146437 and parameters: {'hidden_size1': 160, 'hidden_size2': 176, 'lr': 1.3877516892398722e-05, 'activation': 'ReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:02,713] Trial 15 finished with value: 0.45116868998006887 and parameters: {'hidden_size1': 288, 'hidden_size2': 72, 'lr': 0.0038695692835191363, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:03,302] Trial 16 finished with value: 0.4206815511163337 and parameters: {'hidden_size1': 64, 'hidden_size2': 152, 'lr': 0.00026935002208742554, 'activation': 'ReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:05,074] Trial 17 finished with value: 0.4472396925227114 and parameters: {'hidden_size1': 512, 'hidden_size2': 104, 'lr': 0.0008866070191650927, 'activation': 'ReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:06,083] Trial 18 finished with value: 0.423394495412844 and parameters: {'hidden_size1': 160, 'hidden_size2': 208, 'lr': 3.3402585721302836e-05, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:06,714] Trial 19 finished with value: 0.44048149799375835 and parameters: {'hidden_size1': 224, 'hidden_size2': 56, 'lr': 0.00035266867308168554, 'activation': 'LeakyReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:06,964] Trial 20 finished with value: 0.45107592367032073 and parameters: {'hidden_size1': 128, 'hidden_size2': 104, 'lr': 0.004429955257916865, 'activation': 'ReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:07,435] Trial 21 finished with value: 0.45307563649879207 and parameters: {'hidden_size1': 320, 'hidden_size2': 8, 'lr': 0.0015564318937071483, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:07,998] Trial 22 finished with value: 0.4501922404753583 and parameters: {'hidden_size1': 384, 'hidden_size2': 40, 'lr': 0.004112115089481595, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:08,327] Trial 23 finished with value: 0.4481792717086835 and parameters: {'hidden_size1': 256, 'hidden_size2': 32, 'lr': 0.001076552707407963, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:09,208] Trial 24 finished with value: 0.4492307692307692 and parameters: {'hidden_size1': 480, 'hidden_size2': 64, 'lr': 0.0025620209394219447, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:10,247] Trial 25 finished with value: 0.45400372439478587 and parameters: {'hidden_size1': 352, 'hidden_size2': 96, 'lr': 0.0063496935122904176, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:10,814] Trial 26 finished with value: 0.44831478793742946 and parameters: {'hidden_size1': 256, 'hidden_size2': 144, 'lr': 0.009802478925981238, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:11,348] Trial 27 finished with value: 0.42759595008241114 and parameters: {'hidden_size1': 192, 'hidden_size2': 120, 'lr': 0.0002459711741753114, 'activation': 'Tanh'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:12,477] Trial 28 finished with value: 0.4417633410672854 and parameters: {'hidden_size1': 384, 'hidden_size2': 208, 'lr': 0.0005644151375142971, 'activation': 'LeakyReLU'}. Best is trial 3 with value: 0.45652173913043476.
[I 2025-10-16 20:17:13,756] Trial 29 finished with value: 0.4584323040380047 and parameters: {'hidden_size1': 416, 'hidden_size2': 136, 'lr': 0.0024487023722689107, 'activation': 'ReLU'}. Best is trial 29 with value: 0.4584323040380047.
[I 2025-10-16 20:17:14,839] Trial 30 finished with value: 0.46045384445913196 and parameters: {'hidden_size1': 288, 'hidden_size2': 128, 'lr': 0.006468704393050349, 'activation': 'ReLU'}. Best is trial 30 with value: 0.46045384445913196.
[I 2025-10-16 20:17:15,757] Trial 31 finished with value: 0.4597513755858977 and parameters: {'hidden_size1': 288, 'hidden_size2': 120, 'lr': 0.00608124085504207, 'activation': 'ReLU'}. Best is trial 30 with value: 0.46045384445913196.
[I 2025-10-16 20:17:16,998] Trial 32 finished with value: 0.4607142857142857 and parameters: {'hidden_size1': 288, 'hidden_size2': 128, 'lr': 0.00489606853543318, 'activation': 'ReLU'}. Best is trial 32 with value: 0.4607142857142857.
[I 2025-10-16 20:17:18,186] Trial 33 finished with value: 0.4589382448537378 and parameters: {'hidden_size1': 288, 'hidden_size2': 136, 'lr': 0.005437453721728819, 'activation': 'ReLU'}. Best is trial 32 with value: 0.4607142857142857.
[I 2025-10-16 20:17:18,952] Trial 34 finished with value: 0.4602446483180428 and parameters: {'hidden_size1': 288, 'hidden_size2': 168, 'lr': 0.005579618157322392, 'activation': 'ReLU'}. Best is trial 32 with value: 0.4607142857142857.
[I 2025-10-16 20:17:20,633] Trial 35 finished with value: 0.4564067172762825 and parameters: {'hidden_size1': 352, 'hidden_size2': 168, 'lr': 0.003372718049186081, 'activation': 'ReLU'}. Best is trial 32 with value: 0.4607142857142857.
[I 2025-10-16 20:17:21,927] Trial 36 finished with value: 0.45339168490153176 and parameters: {'hidden_size1': 288, 'hidden_size2': 192, 'lr': 0.006341183443682534, 'activation': 'ReLU'}. Best is trial 32 with value: 0.4607142857142857.
[I 2025-10-16 20:17:22,969] Trial 37 finished with value: 0.45796545105566216 and parameters: {'hidden_size1': 224, 'hidden_size2': 128, 'lr': 0.009530142534606397, 'activation': 'ReLU'}. Best is trial 32 with value: 0.4607142857142857.
[I 2025-10-16 20:17:24,546] Trial 38 finished with value: 0.4585199402857752 and parameters: {'hidden_size1': 352, 'hidden_size2': 152, 'lr': 0.003458930731162161, 'activation': 'ReLU'}. Best is trial 32 with value: 0.4607142857142857.
[I 2025-10-16 20:17:25,664] Trial 39 finished with value: 0.4510446538303974 and parameters: {'hidden_size1': 320, 'hidden_size2': 112, 'lr': 0.0012326314613526936, 'activation': 'ReLU'}. Best is trial 32 with value: 0.4607142857142857.
[I 2025-10-16 20:17:26,889] Trial 40 finished with value: 0.4553812871822607 and parameters: {'hidden_size1': 288, 'hidden_size2': 192, 'lr': 0.005618786957949082, 'activation': 'ReLU'}. Best is trial 32 with value: 0.4607142857142857.
[I 2025-10-16 20:17:28,211] Trial 41 finished with value: 0.4617622610141313 and parameters: {'hidden_size1': 288, 'hidden_size2': 136, 'lr': 0.005119135715864478, 'activation': 'ReLU'}. Best is trial 41 with value: 0.4617622610141313.
[I 2025-10-16 20:17:29,092] Trial 42 finished with value: 0.4596398948007283 and parameters: {'hidden_size1': 256, 'hidden_size2': 120, 'lr': 0.007317735209186232, 'activation': 'ReLU'}. Best is trial 41 with value: 0.4617622610141313.
[I 2025-10-16 20:17:29,751] Trial 43 finished with value: 0.4541097106337653 and parameters: {'hidden_size1': 320, 'hidden_size2': 88, 'lr': 0.0030086095889344973, 'activation': 'ReLU'}. Best is trial 41 with value: 0.4617622610141313.
[I 2025-10-16 20:17:30,680] Trial 44 finished with value: 0.46153846153846156 and parameters: {'hidden_size1': 224, 'hidden_size2': 160, 'lr': 0.004474755645741476, 'activation': 'ReLU'}. Best is trial 41 with value: 0.4617622610141313.
[I 2025-10-16 20:17:31,600] Trial 45 finished with value: 0.44389884605941565 and parameters: {'hidden_size1': 192, 'hidden_size2': 168, 'lr': 0.0018146998345865072, 'activation': 'ReLU'}. Best is trial 41 with value: 0.4617622610141313.
[I 2025-10-16 20:17:34,099] Trial 46 finished with value: 0.4745020792295907 and parameters: {'hidden_size1': 224, 'hidden_size2': 144, 'lr': 0.005290717457324993, 'activation': 'LeakyReLU'}. Best is trial 46 with value: 0.4745020792295907.
[I 2025-10-16 20:17:35,184] Trial 47 finished with value: 0.4588901472253681 and parameters: {'hidden_size1': 224, 'hidden_size2': 144, 'lr': 0.004942472922537854, 'activation': 'LeakyReLU'}. Best is trial 46 with value: 0.4745020792295907.
[I 2025-10-16 20:17:36,546] Trial 48 finished with value: 0.43877300613496933 and parameters: {'hidden_size1': 192, 'hidden_size2': 152, 'lr': 0.00011485283951881726, 'activation': 'LeakyReLU'}. Best is trial 46 with value: 0.4745020792295907.
[I 2025-10-16 20:17:37,263] Trial 49 finished with value: 0.45546875 and parameters: {'hidden_size1': 224, 'hidden_size2': 184, 'lr': 0.0027610904064066877, 'activation': 'LeakyReLU'}. Best is trial 46 with value: 0.4745020792295907.

Best hyperparameters: {'hidden_size1': 224, 'hidden_size2': 144, 'lr': 0.005290717457324993, 'activation': 'LeakyReLU'}

In [25]:
def build_model():
    input_dim = X_train.shape[1]
    
    model = nn.Sequential(
    nn.Linear(input_dim, 224),
    nn.LeakyReLU(),
    nn.Linear(224, 144),
    nn.LeakyReLU(),
    nn.Linear(144, 1),
    nn.Sigmoid()
    )
    
    return model

In [26]:
def train_model(model, train_loader, epochs=100, patience=10):
    set_seed(42)
    criterion = nn.BCELoss()
    optimizer = optim.Adam(model.parameters(), lr= 0.005290717457324993)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5, min_lr=1e-4)

    best_loss = float('inf')
    epochs_no_improve = 0

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0
        for inputs, labels in train_loader:
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        avg_loss = epoch_loss / len(train_loader)
        scheduler.step(avg_loss)

        if avg_loss < best_loss:
            best_loss = avg_loss
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1

        if (epoch + 1) % 10 == 0 or epoch == 0:
            print(f'Epoch [{epoch+1}/{epochs}], Loss: {avg_loss:.4f}')

        if epochs_no_improve >= patience:
            print(f"Early stopping at epoch {epoch+1}")
            break

In [27]:
def test_model(name, model, X_test_t, y_test_t, threshold=0.65):
    set_seed(42)
    model.eval()
    with torch.no_grad():
        logits = model(X_test_t).squeeze(1)
        probs = torch.sigmoid(logits)  # convert logits to probabilities
        y_pred = (probs > threshold).int()

        y_true = y_test_t.squeeze(1).cpu().numpy()
        y_pred_np = y_pred.cpu().numpy()
        probs_np = probs.cpu().numpy()

    create_evaluation_metrics(name, y_true, y_pred_np, probs_np)

In [28]:
input_dim = X_train_orig_t.shape[1]

In [29]:
orig_train_dataset = TensorDataset(X_train_orig_t, y_train_orig_t)
orig_train_loader = DataLoader(orig_train_dataset, batch_size=32, shuffle=True)

In [30]:
NN_orig = build_model()

train_model(NN_orig, orig_train_loader, epochs=100)

Epoch [1/100], Loss: 0.5936
Epoch [10/100], Loss: 0.5800
Epoch [20/100], Loss: 0.5785
Epoch [30/100], Loss: 0.5773
Epoch [40/100], Loss: 0.5760
Epoch [50/100], Loss: 0.5747
Epoch [60/100], Loss: 0.5739
Epoch [70/100], Loss: 0.5735
Epoch [80/100], Loss: 0.5737
Epoch [90/100], Loss: 0.5698
Epoch [100/100], Loss: 0.5682

In [37]:
test_model("Stratified", NN_orig, X_test_t, y_test_t, threshold = 0.59)

Stratified
ROC AUC: 0.6298339161787588
Confusion Matrix:
 [[2788  846]
 [ 887  584]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.76      0.77      0.76      3634
         1.0       0.41      0.40      0.40      1471

    accuracy                           0.66      5105
   macro avg       0.58      0.58      0.58      5105
weighted avg       0.66      0.66      0.66      5105

---------------------------

In [38]:
rus_train_dataset = TensorDataset(X_train_rus_t, y_train_rus_t)
rus_train_loader = DataLoader(rus_train_dataset, batch_size=32, shuffle=True)

In [39]:
NN_rus = build_model()

train_model(NN_rus, rus_train_loader, epochs=100)

Epoch [1/100], Loss: 0.6860
Epoch [10/100], Loss: 0.6668
Epoch [20/100], Loss: 0.6646
Epoch [30/100], Loss: 0.6625
Epoch [40/100], Loss: 0.6604
Epoch [50/100], Loss: 0.6555
Epoch [60/100], Loss: 0.6536
Epoch [70/100], Loss: 0.6525
Epoch [80/100], Loss: 0.6500
Epoch [90/100], Loss: 0.6475
Epoch [100/100], Loss: 0.6453

In [40]:
test_model("RandomUnderSampling", NN_rus, X_test_t, y_test_t)

RandomUnderSampling
ROC AUC: 0.6243919781712635
Confusion Matrix:
 [[2855  779]
 [ 945  526]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.75      0.79      0.77      3634
         1.0       0.40      0.36      0.38      1471

    accuracy                           0.66      5105
   macro avg       0.58      0.57      0.57      5105
weighted avg       0.65      0.66      0.66      5105

---------------------------

In [ ]:
smote_train_dataset = TensorDataset(X_train_smote_t, y_train_smote_t)
smote_train_loader = DataLoader(smote_train_dataset, batch_size=32, shuffle=True)

In [42]:
NN_smote = build_model()

train_model(NN_smote, smote_train_loader, epochs=100)

Epoch [1/100], Loss: 0.6775
Epoch [10/100], Loss: 0.6604
Epoch [20/100], Loss: 0.6563
Epoch [30/100], Loss: 0.6531
Epoch [40/100], Loss: 0.6501
Epoch [50/100], Loss: 0.6473
Epoch [60/100], Loss: 0.6456
Epoch [70/100], Loss: 0.6431
Epoch [80/100], Loss: 0.6413
Epoch [90/100], Loss: 0.6386
Epoch [100/100], Loss: 0.6368

In [43]:
test_model("Smote", NN_smote, X_test_t, y_test_t)

Smote
ROC AUC: 0.6230983007751776
Confusion Matrix:
 [[2956  678]
 [1004  467]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.75      0.81      0.78      3634
         1.0       0.41      0.32      0.36      1471

    accuracy                           0.67      5105
   macro avg       0.58      0.57      0.57      5105
weighted avg       0.65      0.67      0.66      5105

---------------------------

In [ ]:
hybrid_train_dataset = TensorDataset(X_train_hybrid_t, y_train_hybrid_t)
hybrid_train_loader = DataLoader(hybrid_train_dataset, batch_size=32, shuffle=True)

In [45]:
NN_hybrid = build_model()

train_model(NN_hybrid, hybrid_train_loader, epochs=100)

Epoch [1/100], Loss: 0.6767
Epoch [10/100], Loss: 0.6623
Epoch [20/100], Loss: 0.6577
Epoch [30/100], Loss: 0.6547
Epoch [40/100], Loss: 0.6524
Epoch [50/100], Loss: 0.6495
Epoch [60/100], Loss: 0.6482
Epoch [70/100], Loss: 0.6456
Epoch [80/100], Loss: 0.6437
Epoch [90/100], Loss: 0.6404
Epoch [100/100], Loss: 0.6387

In [46]:
test_model("Hybrid", NN_hybrid, X_test_t, y_test_t)

Hybrid
ROC AUC: 0.6237717500739859
Confusion Matrix:
 [[2983  651]
 [1020  451]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.75      0.82      0.78      3634
         1.0       0.41      0.31      0.35      1471

    accuracy                           0.67      5105
   macro avg       0.58      0.56      0.57      5105
weighted avg       0.65      0.67      0.66      5105

---------------------------

## Best model:

<b> RandomForestClassifier with Stratified Sampling and Class Weights </b>

Key Metrics:

- ROC AUC: 🟢 0.6495 (highest among all models)
- Recall (class 1 - churn): 0.42
- Precision (class 1 - churn): 0.43
- F1-score (class 1): 0.42
- Accuracy: 0.67

Why this model?
- Highest ROC AUC: It best distinguishes between churners and non-churners across thresholds.
- Balanced accuracy and F1: It maintains a reasonable balance between detecting churners and avoiding false alarms.
- Good performance on imbalanced data: The class_weight='balanced' parameter compensates for class imbalance without needing resampling tricks like SMOTE or RUS, which can sometimes introduce noise.